In [2]:
import pandas as pd

# Load cleaned dataset
df = pd.read_csv("../data/processed/cleaned_step1.csv")

# Create Revenue column
df["Revenue"] = df["Quantity"] * df["Price"]

# Convert InvoiceDate to datetime
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0

In [3]:
df["Year"] = df["InvoiceDate"].dt.year

df["Year"].head()

0    2009
1    2009
2    2009
3    2009
4    2009
Name: Year, dtype: int32

In [4]:
df["Month"] = df["InvoiceDate"].dt.month

df["Month"].head()

0    12
1    12
2    12
3    12
4    12
Name: Month, dtype: int32

In [5]:
df["Day"] = df["InvoiceDate"].dt.day

df["Day"].head()

0    1
1    1
2    1
3    1
4    1
Name: Day, dtype: int32

In [6]:
df["Weekday"] = df["InvoiceDate"].dt.day_name()

df["Weekday"].head()

0    Tuesday
1    Tuesday
2    Tuesday
3    Tuesday
4    Tuesday
Name: Weekday, dtype: str

In [7]:
df["Hour"] = df["InvoiceDate"].dt.hour

df["Hour"].head()

0    7
1    7
2    7
3    7
4    7
Name: Hour, dtype: int32

In [8]:
df["IsWeekend"] = df["Weekday"].isin(["Saturday", "Sunday"])

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day,Weekday,Hour,IsWeekend
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1,Tuesday,7,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,Tuesday,7,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,Tuesday,7,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1,Tuesday,7,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1,Tuesday,7,False

In [9]:
basket_value = (
    df.groupby("Invoice")["Revenue"]
      .sum()
)

basket_value.head()

Invoice
489434     505.30
489435     145.80
489436     630.33
489437     310.75
489438    2286.24
Name: Revenue, dtype: float64

In [10]:
customer_spending = (
    df.groupby("Customer ID")["Revenue"]
      .sum()
)

customer_spending.head()

Customer ID
12346.0     -51.74
12347.0    1323.32
12348.0     222.16
12349.0    2646.99
12351.0     300.93
Name: Revenue, dtype: float64

In [11]:
purchase_frequency = (
    df.groupby("Customer ID")["Invoice"]
      .nunique()
)

purchase_frequency.head()

Customer ID
12346.0    15
12347.0     2
12348.0     1
12349.0     4
12351.0     1
Name: Invoice, dtype: int64

In [12]:
avg_basket = (
    df.groupby("Invoice")["Quantity"]
      .sum()
)

avg_basket.describe()

count    28816.000000
mean       187.853415
std       1310.111018
min     -87167.000000
25%          1.000000
50%         80.000000
75%        215.000000
max      87167.000000
Name: Quantity, dtype: float64

In [13]:
df.to_csv(
    "../data/processed/feature_engineered.csv",
    index=False
)

print("Feature Engineering Completed!")

Feature Engineering Completed!