In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/processed/feature_engineered.csv")

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,Year,Month,Day,Weekday,Hour,IsWeekend
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009,12,1,Tuesday,7,False
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,Tuesday,7,False
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009,12,1,Tuesday,7,False
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009,12,1,Tuesday,7,False
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009,12,1,Tuesday,7,False

In [3]:
monthly_revenue = (
    df.groupby(df["InvoiceDate"].dt.to_period("M"))["Revenue"]
    .sum()
    .reset_index()
)

monthly_revenue["InvoiceDate"] = monthly_revenue["InvoiceDate"].astype(str)

monthly_revenue.head()

  InvoiceDate     Revenue
0     2009-12  796648.500
1     2010-01  622479.502
2     2010-02  531265.366
3     2010-03  763247.241
4     2010-04  587926.692

In [4]:
top_products = (
    df.groupby("Description")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
    .reset_index()
)

top_products

                           Description    Revenue
0             REGENCY CAKESTAND 3 TIER  162885.71
1   WHITE HANGING HEART T-LIGHT HOLDER  157580.28
2                       DOTCOM POSTAGE  116401.99
3        ASSORTED COLOUR BIRD ORNAMENT   72251.32
4      PAPER CHAIN KIT 50'S CHRISTMAS    57808.25
5              JUMBO BAG RED RETROSPOT   56329.56
6                        PARTY BUNTING   49626.92
7  ROTATING SILVER ANGELS T-LIGHT HLDR   47641.89
8                              POSTAGE   46092.36
9                 JUMBO BAG STRAWBERRY   36668.41

In [5]:
country_sales = (
    df.groupby("Country")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

country_sales.head()

          Country      Revenue
0  United Kingdom  8161692.763
1            EIRE   352235.680
2     Netherlands   263861.760
3         Germany   195920.421
4          France   130661.550

In [6]:
customer_sales = (
    df.groupby("Customer ID")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

customer_sales.head()

   Customer ID    Revenue
0      18102.0  341776.73
1      14646.0  243853.05
2      14156.0  183163.55
3      14911.0  137710.76
4      13694.0  128172.42

In [7]:
monthly_revenue.to_csv(
    "../data/processed/dashboard_monthly.csv",
    index=False
)

top_products.to_csv(
    "../data/processed/dashboard_products.csv",
    index=False
)

country_sales.to_csv(
    "../data/processed/dashboard_country.csv",
    index=False
)

customer_sales.to_csv(
    "../data/processed/dashboard_customers.csv",
    index=False
)

print("Dashboard datasets created successfully!")

Dashboard datasets created successfully!